### ISSUE TITLE
ArchiveTeamWarrior stuck at uploading

### ISSUE THREAD

**Issue by Deses** [JakeShirley/unraid-templates#1]
As stated here: https://forums.unraid.net/topic/138245-support-darknavi-archiveteam-warrior/#comment-1308457
and here: https://github.com/ArchiveTeam/seesaw-kit/issues/145

Warriors are stuck for hours at uploading.

**Comment by TheTechRobo** [comment]
See https://github.com/ArchiveTeam/seesaw-kit/issues/145#issuecomment-1728304787
